# https://dash.cloudflare.com/profile/api-tokens
# You have to create your own cloudflare-api-key
#  ->All zones - DNS Settings:Edit, Zone Settings:Read, Zone:Read, DNS:Edit

dns_cloudflare_api_token=Your_CloudFlare_API_KEY_Here